version: '3.8'

services:
  db:
    image: mysql:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - network
    ports:
      - "3308:3306"

  adminer:
    image: adminer:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      - db
    networks:
      - network
    ports:
      - "8085:8080"

  app:
    image: vaadinapp
    build: ../
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    networks:
      - network
    ports:
      - "8082:8082"

networks:
  network:
    driver: overlay
