version: '3.9'

services:
  db:
    image: mysql:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
    ports:
      - target: 8080
        published: 8080
        mode: host
    networks:
      - frontend
    depends_on:
      - db

  app:
    image: vaadinapp
    build: ../
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
    ports:
      - target: 8082
        published: 8082
        mode: host
    networks:
      - frontend
    depends_on:
      - db

volumes:
  db-data:

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay
