version: '4.8'

services:
  db:
    image: mysql:6.7
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 6s
        max_attempts: 5
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - network
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 6s
        max_attempts: 4
    depends_on:
      - db
    networks:
      - network
    ports:
      - "8086:8080"

  app:
    image: app
    build: ../
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    networks:
      - network
    ports:
      - "8082:8082"

networks:
  network:
    driver: overlay
