version: '3.8'

services:
  db:
    image: mysql:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3308:3306"

  app:
    image: vaadinapp
    build: ../
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    ports:
      - "8082:8082"
